name: Sync Main branch from Standard ecommerce Demo

on:
  workflow_dispatch:

jobs:
  sync_main:
    name: Sync main branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fix permissions
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.2.0.b
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://x-access-token:${GITHUB_TOKEN}@github.com/storyblok/storyblok-demo-ecommerce-storefront.git
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: main
          # Branch to merge into downstream
          downstream_branch: main
          # GitHub Bot token
          token: ${{ secrets.GH_PAT }}
